# Generated by Django 6.0.3 on 2026-04-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_resumeanalysis_id_resumeanalysis_analysis_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeanalysis',
            name='analysis_id',
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
