# Generated by Django 6.0.3 on 2026-04-21 14:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_resumeanalysis_analysis_id_resumeanalysis_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeanalysis',
            name='id',
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='analysis_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
