# Generated by Django 6.0.3 on 2026-04-22 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_resumeanalysis_id_resumeanalysis_analysis_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeanalysis',
            name='jd',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(150, message='Job description must be at least 150 characters long')]),
        ),
    ]
