# Generated by Django 6.0.3 on 2026-04-24 07:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_resumeanalysis_jd'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
