# Generated by Django 6.0.3 on 2026-05-03 05:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_coupon_claimed_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
