# Generated by Django 6.0.3 on 2026-04-24 12:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('interview_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resume', models.FileField(upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('jd', models.TextField(validators=[django.core.validators.MinLengthValidator(150)])),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('in_progress', 'In Progress'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='created', max_length=100)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=100)),
                ('experience', models.CharField(choices=[('fresher', 'Fresher (0 years)'), ('junior', '1–3 years'), ('mid', '3–5 years'), ('senior', '5+ years')], default='fresher', max_length=100)),
                ('llm_cost', models.PositiveIntegerField(default=0)),
                ('credits_used', models.PositiveIntegerField(default=0)),
                ('cheating_count', models.PositiveIntegerField(default=0)),
                ('overall_cost', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(max_length=200, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAndAnswer',
            fields=[
                ('question_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_no', models.PositiveIntegerField(default=0)),
                ('expected_answer', models.TextField(blank=True, null=True)),
                ('answer_audio_file', models.FileField(blank=True, null=True, upload_to='answers/')),
                ('answer_audio_transcript', models.TextField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question_domain', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(max_length=200, unique=True)),
                ('analysis_json', models.JSONField(blank=True, default=dict, null=True)),
                ('llm_cost', models.PositiveIntegerField(default=0)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.interview')),
            ],
        ),
    ]
