# Generated by Django 6.0.3 on 2026-04-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_alter_interview_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionandanswer',
            name='question',
            field=models.TextField(default='adf'),
            preserve_default=False,
        ),
    ]
