# Generated by Django 6.0.3 on 2026-04-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_questionandanswer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionandanswer',
            name='category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='questionandanswer',
            name='question_domain',
            field=models.CharField(max_length=200),
        ),
    ]
