"""
Django settings for AI_mock_interviewer project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

ENVIRONMENT = os.getenv("ENVIRONMENT")

if ENVIRONMENT == 'production':
    ALLOWED_HOSTS= ['4.188.83.169','mockzen.tech','www.mockzen.tech']
    DJANGO_CSRF_TRUSTED_ORIGINS= ["http://4.188.83.169","https://4.188.83.169",'https://www.mockzen.tech','http://mockzen.tech']
else:
    ALLOWED_HOSTS = []

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    # 'daphne',
    'django.contrib.staticfiles',

    # 'channels',
    'core.apps.CoreConfig',
    'interview.apps.InterviewConfig',
    'payment.apps.PaymentConfig',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    'storages',
    'admin_honeypot',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware",

]

ROOT_URLCONF = 'AI_mock_interviewer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # `allauth` needs this from django
                'django.template.context_processors.request',
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# ASGI_APPLICATION = "AI_mock_interviewer.asgi.application"
WSGI_APPLICATION = 'AI_mock_interviewer.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


import dj_database_url

# Use remote DB when provided, otherwise fall back to local sqlite for dev.
NEON_DB_URL = os.environ.get('NEON_DB_URL')
if NEON_DB_URL:
    DATABASES = {
        'default': dj_database_url.parse(
            NEON_DB_URL,
            conn_max_age=600,
            ssl_require=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/


STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

SOCIALACCOUNT_LOGIN_ON_GET = True
ACCOUNT_LOGOUT_ON_GET = True
LOGIN_REDIRECT_URL = 'home'
ACCOUNT_LOGIN_CANCEL_REDIRECT_URL = '/'
ACCOUNT_SOCIALACCOUNT_LOGIN_CANCELLED_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = 'home'

GROQ_API_KEY = os.getenv("GROQ_API_KEY")
OPEN_ROUTER_KEY = os.getenv("OPEN_ROUTER")

USE_TZ = True
TIME_ZONE = "Asia/Kolkata"

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        }
    }
}

CASHFREE_CLIENT_ID = os.getenv("cashfree_client_id")
CASHFREE_CLIENT_SECRET = os.getenv("CASHFREE_CLIENT_SECRET")
CASHFREE_ENVIRONMENT = os.getenv("CASHFREE_ENV")
CASHFREE_CALLBACK_URL = "payment_verify"
AI_CREDITS_API = os.getenv("AI_CREDITS_API")

# azure blob setup

AZURE_ACCOUNT_NAME = os.getenv('AZURE_ACCOUNT_NAME')
AZURE_ACCOUNT_KEY = os.getenv('AZURE_ACCOUNT_KEY')
AZURE_ACCOUNT_CONNECTION_STRING = os.getenv('AZURE_ACCOUNT_CONNECTION_STRING')
AZURE_ACCOUNT_CONTAINER = os.getenv('AZURE_ACCOUNT_CONTAINER')

# MEDIA_URL = "media/"
# MEDIA_ROOT = os.path.join(BASE_DIR,"media")


azure_storages = {
    "default": {
        "BACKEND": "storages.backends.azure_storage.AzureStorage",
        "OPTIONS": {
            "account_name": AZURE_ACCOUNT_NAME,
            "account_key": AZURE_ACCOUNT_KEY,
            "azure_container": AZURE_ACCOUNT_CONTAINER,
            "overwrite_files": False,
        },
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },

}

# In development prefer local filesystem storage to avoid network latency.
# if DEBUG:
#     DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
#     MEDIA_ROOT = BASE_DIR / 'media'
#     MEDIA_URL = '/media/'
# else:
#     STORAGES = azure_storages
#     MEDIA_URL = f'https://{AZURE_ACCOUNT_NAME}.blob.core.windows.net/{AZURE_ACCOUNT_CONTAINER}/'


STORAGES = azure_storages
MEDIA_URL = f'https://{AZURE_ACCOUNT_NAME}.blob.core.windows.net/{AZURE_ACCOUNT_CONTAINER}/'

DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800